import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';

const db = new PGlite();
const video = n => `track${String(n).padStart(6, '0')}`;
try {
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create schema jukebox_private;
    create function jukebox_private.secret_ok() returns boolean language sql stable as $$
      select coalesce(current_setting('request.headers',true),'{}')::jsonb->>'x-jukebox-secret'='test-only'
    $$;
    create table jukebox_private.queue (
      id bigint generated by default as identity primary key,
      video_id text not null, title text not null, artist text not null default '', thumbnail text not null default '',
      requested_by text not null default '', requester_id text not null default '',
      votes integer not null default 0, priority integer not null default 0,
      priority_requested boolean not null default false, status text not null default 'queued',
      created_at bigint not null default 0, started_at bigint, finished_at bigint,
      check(priority>=0 or (requester_id='autodj' and priority=-100))
    );
    create unique index active_video on jukebox_private.queue(video_id) where status in ('playing','queued');
    create table jukebox_private.votes (
      id bigint generated by default as identity primary key, queue_id bigint references jukebox_private.queue(id),
      voter_id text not null, created_at bigint not null, unique(queue_id,voter_id)
    );
    create table jukebox_private.player_state (
      id integer primary key, revision bigint not null default 0, action text not null default 'sync',
      updated_at bigint not null default 0, volume integer not null default 80, night_mode boolean not null default false
    );
    insert into jukebox_private.player_state(id) values(1);
    alter table jukebox_private.queue enable row level security;
    alter table jukebox_private.votes enable row level security;
    alter table jukebox_private.player_state enable row level security;
    create policy backend_queue on jukebox_private.queue to anon using(jukebox_private.secret_ok()) with check(jukebox_private.secret_ok());
    create policy backend_votes on jukebox_private.votes to anon using(jukebox_private.secret_ok()) with check(jukebox_private.secret_ok());
    create policy backend_player on jukebox_private.player_state to anon using(jukebox_private.secret_ok()) with check(jukebox_private.secret_ok());
    grant usage on schema jukebox_private to anon;
    grant select,insert,update on all tables in schema jukebox_private to anon;
    grant usage,select on all sequences in schema jukebox_private to anon;
  `);
  // Real existing RPC bodies, copied without credentials from the deployed baseline.
  await db.exec(fs.readFileSync(new URL('./fixtures/existing-core-rpcs.sql', import.meta.url), 'utf8'));
  const directory = new URL('../../supabase/migrations/', import.meta.url);
  const filename = fs.readdirSync(directory).find(name => name.endsWith('_continue_last_playlist.sql'));
  await db.exec(fs.readFileSync(new URL(filename, directory), 'utf8'));
  const followup = fs.readdirSync(directory).find(name => name.endsWith('_replace_invalid_autodj_buffer.sql'));
  await db.exec(fs.readFileSync(new URL(followup, directory), 'utf8'));
  const rpc = async (action, payload = {}) => (await db.query(
    'select public.jukebox_continuation_rpc($1,$2::jsonb) as result', [action, JSON.stringify(payload)],
  )).rows[0].result;
  const core = async action => (await db.query('select public.jukebox_rpc($1) as result', [action])).rows[0].result;
  const payload = (n, source_playlist='cz_funk') => ({video_id: video(n), title: `Music ${n}`, source_playlist,
    requester_id: 'guest-a', playlist_label: source_playlist==='cz_oldies' ? 'České oldies' : 'Český funk'});
  const queue = async () => (await db.query('select id,video_id,status,source_playlist from jukebox_private.queue order by id')).rows;
  await db.exec(`set role anon; set request.headers='{}';`);
  assert.equal((await rpc('status'))._status, 401);
  assert.equal((await rpc('add_song', payload(1)))._status, 401);
  await db.exec(`set request.headers='{"x-jukebox-secret":"test-only"}';`);
  assert.equal((await rpc('add_song', payload(1, 'untrusted')))._status, 422);
  const first = await rpc('add_song', payload(1));
  assert.equal(first.source_playlist, 'cz_funk');
  assert.equal('requester_id' in first, false);
  assert.equal((await rpc('add_song', payload(1)))._status, 409);
  await core('player_start');
  assert.equal((await rpc('status')).continuation.id, first.id);
  let buffered = await rpc('prepare', {...payload(2), continuation_id: first.id});
  assert.equal(buffered.song.source_playlist, 'cz_funk');
  const invalidBufferId = buffered.song.id;
  await db.exec(`reset role; update jukebox_private.queue set title='Monkey Business (Upoutávka)' where id=${invalidBufferId}; set role anon;`);
  buffered = await rpc('prepare', {...payload(34), continuation_id:first.id, replace_song_id:invalidBufferId});
  assert.notEqual(buffered.song.id,invalidBufferId,'invalid buffer can be replaced within the same playlist');
  const lateReplacement = await rpc('prepare', {...payload(35), continuation_id:first.id, replace_song_id:invalidBufferId});
  assert.equal(lateReplacement.song.id,buffered.song.id,'late correction preserves the newer buffer');
  const otherGuest = await rpc('add_song', {...payload(3, 'cz_oldies'), requester_id: 'guest-b'});
  assert.equal((await rpc('status')).continuation.source_playlist, 'cz_funk', 'queued guest does not change current playlist');
  const next = await core('player_ended');
  assert.equal(next.song.id, otherGuest.id, 'guest queue stays ahead of AutoDJ');
  const beforeStale = await queue();
  assert.deepEqual(await rpc('prepare', {...payload(4), continuation_id: first.id}), {prepared:false, reason:'stale'});
  assert.deepEqual(await queue(), beforeStale, 'late search cannot remove another playlist buffer');
  const replacement = await rpc('prepare', {...payload(4, 'cz_oldies'), continuation_id: otherGuest.id});
  assert.equal(replacement.song.source_playlist, 'cz_oldies');
  assert.equal((await queue()).find(row => row.id===buffered.song.id).status, 'removed');
  assert.equal((await rpc('status')).continuation.id, otherGuest.id);
  assert.equal((await rpc('status')).recent_video_ids.includes(video(2)), true, 'rejected AutoDJ candidates stay excluded');
  assert.equal('requester_id' in (await rpc('status')).song, false);
  await db.exec(`reset role; update jukebox_private.queue set status='removed' where requester_id='autodj' and status='queued';
    insert into jukebox_private.queue(video_id,title,requester_id,status,started_at,finished_at)
      select 'track'||lpad(i::text,6,'0'),'Old music','autodj','done',i,i from generate_series(10,20) i;
    set role anon;`);
  assert.equal((await rpc('status')).recent_video_ids.includes(video(10)), true);
  assert.deepEqual(await rpc('prepare', {...payload(10, 'cz_oldies'), continuation_id: otherGuest.id}), {prepared:false,reason:'recent'}, 'full history beyond six videos');
  assert.deepEqual(await rpc('prepare', {...payload(3, 'cz_oldies'), continuation_id: otherGuest.id}), {prepared:false,reason:'recent'}, 'active guest is never duplicated');
  // A display name cannot forge legacy playlist provenance.
  await db.exec(`reset role; update jukebox_private.queue set source_playlist='',requested_by='AutoDJ · České oldies' where id=${otherGuest.id}; set role anon;`);
  assert.equal((await rpc('status')).continuation.id, first.id);
  await db.exec(`reset role; update jukebox_private.queue set requester_id='autodj',requested_by='AutoDJ · Retro Soul & Blues' where id=${otherGuest.id}; set role anon;`);
  assert.equal((await rpc('status')).continuation.source_playlist, 'soul_blues', 'real legacy AutoDJ remains compatible');
  assert.equal((await rpc('add_song', {...payload(30,'custom:rock 80. let'),requester_id:'admin'})).source_playlist, 'custom:rock 80. let');
  // Failure while assigning source must roll the complete guest insertion back.
  await db.exec(`reset role;
    create function jukebox_private.fail_source() returns trigger language plpgsql as $$ begin raise exception 'test source failure'; end $$;
    create trigger fail_source before update of source_playlist on jukebox_private.queue for each row execute function jukebox_private.fail_source();
    set role anon;`);
  const beforeFailure = await queue();
  await assert.rejects(rpc('add_song', {...payload(31), requester_id:'admin'}), /test source failure/);
  assert.deepEqual(await queue(), beforeFailure, 'atomic source + guest insertion');
  await db.exec('reset role;');
  const flags = (await db.query(`select prosecdef,has_function_privilege('authenticated',oid,'execute') as authenticated_access
    from pg_proc where proname='jukebox_continuation_rpc'`)).rows[0];
  assert.equal(flags.prosecdef, false);
  assert.equal(flags.authenticated_access, false);
  console.log('PostgreSQL continuation: source persistence, legacy context, full history, guest ordering, stale search, secret/RLS and rollback passed.');
} catch (error) {
  console.error(error.message, error.detail || '', error.where || '', error.stack?.split('\n').slice(-3).join('\n') || '');
  process.exitCode = 1;
} finally { await db.close(); }
